/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true,
      "siteStorageNamespacing": true,
      "fasterByDefault": true,
      "mdx1CompatDisabledByDefault": true
    },
    "experimental_vcs": {},
    "experimental_router": "browser",
    "faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true,
      "gitEagerVcs": true
    }
  },
  "title": "Chaos Mesh",
  "tagline": "A Powerful Chaos Engineering Platform for Kubernetes",
  "favicon": "/img/favicon.ico",
  "url": "https://chaos-mesh.org",
  "baseUrl": "/zh/",
  "organizationName": "chaos-mesh",
  "projectName": "chaos-mesh.github.io",
  "onBrokenLinks": "warn",
  "trailingSlash": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "zh"
    ],
    "localeConfigs": {
      "en": {
        "label": "English"
      },
      "zh": {
        "label": "简体中文"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "classic",
      {
        "gtag": {
          "trackingID": "G-T31S4LR9LL"
        },
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/chaos-mesh/website/edit/master/",
          "editLocalizedFiles": true
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/chaos-mesh/website/edit/master/",
          "editLocalizedFiles": true
        },
        "theme": {
          "customCss": "./src/styles/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "image": "/img/chaos-mesh-social-preview.png",
    "algolia": {
      "appId": "3BY0S3HQX6",
      "apiKey": "99bb3af44d57f0e8f6d7e019d7e2c2d7",
      "indexName": "chaos-mesh",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "Chaos Mesh",
      "logo": {
        "alt": "Chaos Mesh",
        "src": "img/logos/logo-mini.svg",
        "srcDark": "img/logos/logo-mini-white.svg"
      },
      "items": [
        {
          "to": "docs",
          "label": "文档",
          "position": "left"
        },
        {
          "to": "blog",
          "label": "博客",
          "position": "left"
        },
        {
          "href": "https://community.cncf.io/chaos-mesh-community/",
          "label": "社团",
          "position": "left"
        },
        {
          "to": "contact",
          "label": "Contact Us",
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "dropdownItemsAfter": [
            {
              "type": "html",
              "value": "<hr style=\"margin: .5em 0;\" />"
            },
            {
              "to": "/versions",
              "label": "All Versions"
            },
            {
              "to": "/supported-releases",
              "label": "Supported Releases"
            }
          ],
          "position": "right",
          "dropdownItemsBefore": []
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/chaos-mesh/chaos-mesh",
          "className": "header-github-link",
          "aria-label": "GitHub",
          "position": "right"
        }
      ]
    },
    "footer": {
      "links": [
        {
          "title": "文档",
          "items": [
            {
              "label": "快速试用",
              "to": "docs/quick-start"
            },
            {
              "label": "运行实验",
              "to": "docs/run-a-chaos-experiment"
            },
            {
              "label": "开发指南概览",
              "to": "docs/developer-guide-overview"
            },
            {
              "label": "常见问题",
              "to": "docs/faqs"
            }
          ]
        },
        {
          "title": "社区",
          "items": [
            {
              "label": "博客",
              "to": "blog"
            },
            {
              "label": "CNCF 社团",
              "href": "https://community.cncf.io/chaos-mesh-community/"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/chaos-mesh/chaos-mesh"
            },
            {
              "label": "Slack (#project-chaos-mesh)",
              "href": "https://slack.cncf.io/"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/chaos_mesh"
            }
          ]
        },
        {
          "title": "致谢",
          "items": [
            {
              "label": "Technology illustrations by Storyset",
              "href": "https://storyset.com/technology"
            },
            {
              "html": "\n                <a href=\"https://www.netlify.com\" target=\"_blank\" rel=\"noopener noreferrer\">\n                  <img src=\"https://www.netlify.com/v3/img/components/netlify-color-bg.svg\" alt=\"Deploys by Netlify\" />\n                </a>\n              "
            },
            {
              "html": "\n                <img\n                  referrerpolicy=\"no-referrer-when-downgrade\"\n                  src=\"https://static.scarf.sh/a.png?x-pxid=3103bfa4-2073-4b9a-bdac-f36f63d979a4\"\n                />\n              "
            }
          ]
        }
      ],
      "copyright": "\n        <p style=\"font-weight: 500;\">Copyright © Chaos Mesh Authors 2026 | Documentation Distributed under CC-BY-4.0</p>\n        © 2026 The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href=\"https://www.linuxfoundation.org/trademark-usage/\"> Trademark Usage</a> page.\n      ",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "#f25c7c"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    "./docusaurus-tailwind-v3",
    [
      "@gracefullight/docusaurus-plugin-microsoft-clarity",
      {
        "projectId": "lggqck9srz"
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": true
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": false,
      "admonitions": false,
      "headingIds": false
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
